"""Command-line transcript for the Gemini replay.

Demo role: run isolated scenarios and verify the evidence generated by this run.
Gemini action it addresses: #1–3, comparing direct and contracted execution.
Must never import: world or CROA signing/firewall implementations; use runtime.
"""

import argparse
from collections.abc import Sequence
from pathlib import Path

from agent.scripted_agent import PLANS, run_plan
from croa.c5_evidence import EvidenceLog
from runtime import RegistryOptions, build_runtime
from transcript import print_scenario


def _run_scenario(
    scenario: str, mode: str, evidence: EvidenceLog, options: RegistryOptions,
) -> None:
    """Use a fresh World and tool adapter for each selected execution mode."""
    ungoverned = governed = None
    if mode in ("ungoverned", "both"):
        ungoverned = run_plan(PLANS[scenario], build_runtime("ungoverned").tools)
    if mode in ("governed", "both"):
        runtime = build_runtime("governed", evidence, options=options)
        governed = run_plan(PLANS[scenario], runtime.tools)
    print_scenario(scenario, ungoverned, governed)


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    """Parse scenario selection and explicit registry demonstrations."""
    parser = argparse.ArgumentParser(description="Local, scripted Gemini replay")
    parser.add_argument("--mode", choices=("ungoverned", "governed", "both"),
                        default="ungoverned")
    parser.add_argument("--scenario", choices=tuple(PLANS))
    parser.add_argument("--ambiguous", action="store_true",
                        help="Register a second host with the same company name")
    parser.add_argument("--registry-mistake", action="store_true",
                        help="Deliberately register the real .com host")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Print selected modes and finish with verification of their evidence chain.

    Args:
        argv: Optional argument sequence; None uses command-line arguments.
    Returns:
        Zero for an intact chain, otherwise one.
    Raises:
        SystemExit: If argparse handles help or rejects an invalid option.
        OSError: If evidence cannot be initialized, written, or verified.
    """
    args = _parse_args(argv)
    options = RegistryOptions(args.ambiguous, args.registry_mistake)
    scenarios = (args.scenario,) if args.scenario else tuple(PLANS)
    path = Path("evidence/evidence.jsonl")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("", encoding="utf-8")
    evidence = EvidenceLog(path)
    if options.registry_mistake:
        print("!!! REGISTRY MISTAKE ACTIVE: real .com host is registered !!!\n")
    for scenario in scenarios:
        _run_scenario(scenario, args.mode, evidence, options)
    print(f"Completed {len(scenarios)} {args.mode} scenario(s).")
    chain = evidence.verify_chain()
    status = chain.reason if chain.ok else f"{chain.reason} at link {chain.broken_link}"
    print(f"C5 evidence: {chain.records} records, chain {status}")
    return 0 if chain.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
