"""Command-line transcript for the Gemini replay.

Demo role: run isolated scenarios and verify the evidence generated by this run.
Gemini action it addresses: #1–3 plus direct execution-firewall bypass attempts.
Must never import: world or CROA signing/firewall implementations; use runtime.
"""

import argparse
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from agent.bypass_tools import BypassTools
from agent.scripted_agent import PLANS, StepResult, run_plan
from croa.c5_evidence import EvidenceLog
from croa.reasons import DENY, PERMIT
from models import FLAG
from runtime import RegistryOptions, build_runtime
from summary import print_summary, summary_row
from transcript import print_scenario


@dataclass(frozen=True)
class ScenarioRun:
    """The selected-mode results for one scenario."""

    scenario: str
    ungoverned: list[StepResult] | None
    governed: list[StepResult] | None


def _run_s4(evidence: EvidenceLog, options: RegistryOptions) -> list[StepResult]:
    """Redeem S0 normally, then run S4 against those consumed contracts."""
    runtime = build_runtime("governed", evidence, options=options, bypass=True)
    if not isinstance(runtime.tools, BypassTools):
        raise TypeError("S4 requires BypassTools")
    setup = run_plan(PLANS["S0"], runtime.tools)
    if setup[-1].output != FLAG:
        raise RuntimeError("S4 contract setup did not complete")
    return run_plan(PLANS["S4"], runtime.tools)


def _s4_not_applicable() -> list[StepResult]:
    """Represent the absence of C6 in ungoverned mode without executing a bypass."""
    return [
        StepResult(step, step.target, step.ungoverned_output)
        for step in PLANS["S4"]
    ]


def _run_scenario(
    scenario: str, mode: str, evidence: EvidenceLog, options: RegistryOptions,
) -> ScenarioRun:
    """Use a fresh World and tool adapter for each selected execution mode."""
    ungoverned = governed = None
    if mode in ("ungoverned", "both"):
        if scenario == "S4":
            ungoverned = _s4_not_applicable()
        else:
            ungoverned = run_plan(PLANS[scenario], build_runtime("ungoverned").tools)
    if mode in ("governed", "both"):
        if scenario == "S4":
            governed = _run_s4(evidence, options)
        else:
            runtime = build_runtime("governed", evidence, options=options)
            governed = run_plan(PLANS[scenario], runtime.tools)
    print_scenario(scenario, ungoverned, governed)
    return ScenarioRun(scenario, ungoverned, governed)


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    """Parse scenario selection and explicit registry demonstrations."""
    parser = argparse.ArgumentParser(description="Local, scripted Gemini replay")
    parser.add_argument("--mode", choices=("ungoverned", "governed", "both"),
                        default="both")
    parser.add_argument("--scenario", choices=tuple(PLANS))
    parser.add_argument("--ambiguous", action="store_true",
                        help="Register a second host with the same company name")
    parser.add_argument("--registry-mistake", action="store_true",
                        help="Deliberately register the real .com host")
    return parser.parse_args(argv)


def _expected_component(scenario: str, options: RegistryOptions) -> str:
    """Return the component that must decide the governed scenario."""
    if scenario == "S0":
        return PERMIT
    if scenario == "S1":
        return "C2" if options.registry_mistake and not options.ambiguous else "C3"
    if scenario == "S3":
        return "C2" if options.registry_mistake else "C3"
    return {"S2": "C4", "S4": "C6"}[scenario]


def _actual_component(run: ScenarioRun) -> str | None:
    """Return the first governed denial, or PERMIT for a completed S0 solve."""
    if run.governed is None:
        return None
    for row in run.governed:
        for trace in row.traces:
            if trace.verdict == DENY:
                return trace.component
    if run.scenario == "S0" and run.governed[-1].output == FLAG:
        return PERMIT
    return None


def main(argv: Sequence[str] | None = None) -> int:
    """Print selected modes and finish with verification of their evidence chain.

    Args:
        argv: Optional argument sequence; None uses command-line arguments.
    Returns:
        Zero when evidence and governed outcomes pass, otherwise one.
    Raises:
        SystemExit: If argparse handles help or rejects an invalid option.
        OSError: If evidence cannot be initialized, written, or verified.
    """
    args = _parse_args(argv)
    options = RegistryOptions(args.ambiguous, args.registry_mistake)
    scenarios = (args.scenario,) if args.scenario else tuple(PLANS)
    path = Path("evidence/evidence.jsonl")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("", encoding="utf-8")
    evidence = EvidenceLog(path)
    if options.registry_mistake:
        print("!!! REGISTRY MISTAKE ACTIVE: real .com host is registered !!!\n")
    runs = [_run_scenario(scenario, args.mode, evidence, options)
            for scenario in scenarios]
    print_summary([
        summary_row(run.scenario, run.ungoverned, run.governed) for run in runs
    ])
    print(f"Completed {len(scenarios)} {args.mode} scenario(s).")
    chain = evidence.verify_chain()
    status = chain.reason if chain.ok else f"{chain.reason} at link {chain.broken_link}"
    print(f"C5 evidence: {chain.records} records, chain {status}")
    governed_ok = all(
        run.governed is None
        or _actual_component(run) == _expected_component(run.scenario, options)
        for run in runs
    )
    return 0 if chain.ok and governed_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
